### ISSUE TITLE
Dragging on maximized window causes it to fullscreen on secondary monitor

### ISSUE THREAD

**Issue by ygaeia** [seleznev/firefox-extension-htitle#55]
If I drag down on a maximized window's titlebar to unmaximize it, as is the default behavior in Gnome, Firefox enters fullscreen mode instead of unmaximizing.  Using Ubuntu Gnome 14.10, Firefox 35.

**Comment by seleznev** [comment]
Please try to disable legacy mode or just remove HTitle.

**Comment by ygaeia** [comment]
Sorry, legacy mode is disabled. I have "Hide titlebar always" on, and HTitle is the only extension enabled.

**Comment by seleznev** [comment]
Not sure that is bug in Htitle. It looks more like bad implementation in xulrunner, because:

* Htitle in default mode doesn't do anything with Firefox's (xul) windows.
* I saw that problem with Thunderbird, but Thunderbird shouldn't switch in fullscreen mode in any case.

Sorry, I don't think that I will fix them quickly. :(

**Comment by ygaeia** [comment]
Well, I switched to Fedora 21 with Gnome 3.14 and the bug doesn't happen any longer.  Perhaps it is an Ubuntu / Gnome 3.12 bug.
